
#数据库相关
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/vue
    password: 10086
    driver-class-name: com.mysql.jdbc.Driver


  mvc:
    static-path-pattern: /images/**
  web:
    resources:
      static-locations: ['classpath:/static/', 'classpath:/public/', 'classpath:/resources/', 'classpath:/META-INF/resources/', 'file:${user.dir}/src/Pic/']
  servlet:
    multipart:
      max-request-size: 5GB
      max-file-size: 5GB

